Angular
karsv/atm pull request #4
Opened 2020-05-09 17:56 UTC by karsv

2020-05-13 12:50 UTC, boroda4436 commented on src/main/java/com/example/atm/controller/AtmController.java
> +    @GetMapping("/get-atms")
```suggestion
    @GetMapping("/")
```
По RESTful best practices - для отримання списку всіх достатньо звернутися на таку url

2020-05-13 13:04 UTC, boroda4436 requested changes

2020-05-13 16:12 UTC, karsv commented on src/main/java/com/example/atm/controller/AtmController.java
> +    @GetMapping("/get-atms")
+

2020-05-13 16:13 UTC, karsv commented on src/main/java/com/example/atm/controller/AtmController.java
>      @PostMapping("/push-cash-to-atm")
+

2020-05-13 17:11 UTC, karsv commented on src/main/java/com/example/atm/controller/AtmController.java
> +            for (Map.Entry<Cash, Long> e : cash.entrySet()) {
я думаю так не вийде, noneMatch boolean повіертає, а для elseThrow потрібен Optional.

2020-05-13 17:13 UTC, karsv commented on src/main/java/com/example/atm/controller/AtmController.java
> +                    cash).toString();
+

2020-05-13 17:14 UTC, karsv commented on src/main/java/com/example/atm/controller/AtmController.java
>              logger.error(e.getMessage());
+

2020-05-13 17:16 UTC, karsv commented on src/main/java/com/example/atm/controller/AtmController.java
> +        AccountRequestDto account = new AccountRequestDto();
+

2020-05-13 17:18 UTC, karsv commented on src/main/java/com/example/atm/controller/AtmController.java
>              } catch (RuntimeException e) {
nope(

2020-05-13 17:24 UTC, karsv commented on src/main/java/com/example/atm/controller/AuthenticateController.java
> +        if (login.isPresent()) {
+

2020-05-13 17:49 UTC, karsv commented on src/main/java/com/example/atm/dto/WithdrawMoneyRequestDto.java
> +    private Long atm;
+

2020-05-13 17:50 UTC, karsv commented on src/main/java/com/example/atm/service/AtmService.java
>      Atm addAtm(Atm atm);
+

2020-05-13 17:52 UTC, karsv commented on src/main/java/com/example/atm/service/AtmService.java
>      Map<Cash, Long> getCashFromAtm(AtmRequestDto atm);
agree)

2020-05-19 08:31 UTC, Sofasmile commented on src/main/java/com/example/atm/controller/AccountController.java
> +    @PostMapping("/account-status")
чому пост метод? тут же не відбувається ніякого створення? ти просто дістаєш дані

2020-05-19 08:31 UTC, Sofasmile commented on src/main/java/com/example/atm/controller/AtmController.java
> +    @GetMapping("/")
```suggestion
    @GetMapping
```

2020-05-19 08:32 UTC, Sofasmile commented
чомусь тревіс повалився, переглянь в чому проблема

2020-05-19 08:38 UTC, karsv commented on src/main/java/com/example/atm/controller/AccountController.java
> +    @PostMapping("/account-status")
ну там же предається тіло запиту

2020-05-19 08:39 UTC, karsv commented
> чомусь тревіс повалився, переглянь в чому проблема

по ходу то проблема  тревіса була

2020-05-21 10:40 UTC, Sofasmile commented on src/main/java/com/example/atm/controller/AccountController.java
> +    @PostMapping("/account-status")
```suggestion
    @PostMapping("/status")
```

2020-05-21 10:40 UTC, Sofasmile commented on src/main/java/com/example/atm/controller/AccountController.java
> +    @PostMapping("/account-status")
_ну там же предається тіло запиту_
це в цілях безпеки?

2020-05-21 10:40 UTC, Sofasmile commented on src/main/java/com/example/atm/dto/PersonRegistrationDto.java
> +    @NotNull(message = "Must be password!")
не зовсім зрозуміле повідомлення

2020-05-21 10:40 UTC, Sofasmile commented on src/main/java/com/example/atm/dto/PersonRegistrationDto.java
> +    @NotNull(message = "User must have name!")
А якщо я введу ім'я Ira - мені прийде повідомлення "User must have name!"???

2020-05-21 10:40 UTC, Sofasmile commented on src/main/java/com/example/atm/dto/PersonRegistrationDto.java
> +    @NotNull(message = "Must repeat password!")
В NotNull - "Must repeat password!"?

2020-05-21 15:50 UTC, karsv commented
> ну там же предається тіло запиту
> це в цілях безпеки?

так, моя ідея була така: що в гет запиті не афішувати номер аакаунту, то передати в тілі

2020-05-22 09:13 UTC, Sofasmile approved these changes

2020-05-22 09:15 UTC, merged